config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users
  resources :garage

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garage.rb
class Garage < ApplicationRecord
  validates :make, :model, presence: true, length: { minimum: 3 }
  validates :year, length: { minimum: 4 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :user, :password, presence: true,
                              length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/garage_controller.rb
class GarageController < ApplicationController
  def index
    @garage = Garage.all
  end

  def show
    @garage = Garage.find(params[:id])
  end

  def edit
    @garage = Garage.find(params[:id])
  end

  def new
    @garage = Garage.new
  end

  def create
    @garage = Garage.new(garage_params)

    if @garage.save
      redirect_to @garage
    else
      render 'new'
    end
  end

  def update
    @garage = Garage.find(params[:id])

    if @garage.update(garage_params)
        redirect_to @garage
      else
        render 'edit'
      end
    end

  def destroy
    @garage = Garage.find(params[:id])
    @garage.destroy

    redirect_to garage_index_path
  end



  private
    def garage_params
      params.require(:garage).permit(:make, :model, :year)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
    redirect_to @user
  else
    render 'new'
  end
end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:user, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garage_helper.rb
module GarageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/garage/_form.html.erb
<%= form_for :garage, url: garage_index_path do |f| %>

  <% if @garage.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@garage.errors.count, "error") %>
prohibited
      this vehicle from being saved:
    </h2>
    <ul>
      <% @garage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<p>
  <%= f.label :make %><br>
  <%= f.text_field :make %>
</p>

<p>
  <%= f.label :model %><br>
  <%= f.text_field :model %>
</p>

<p>
  <%= f.label :year %><br>
  <%= f.text_field :year %>
</p>

<p>
 <%= f.submit "Save Vehicle" %>
</p>

<% end %>

app/views/garage/edit.html.erb
<h1>Edit Vehicle</h1>

<%= form_for :garage, url: garage_path(@garage), method: :patch do |f| %>

  <% if @garage.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@garage.errors.count, "error") %> prohibited
        this vehicle from being saved:
      </h2>
      <ul>
        <% @garage.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </p>

  <p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.submit "Update Vehicle" %>
  </p>

<% end %>

<%= link_to 'Back to Garage', garage_index_path %>

app/views/garage/index.html.erb
<h1> My Vehicles </h1>
<%= link_to 'New Vehicle', new_garage_path %>
<br>
<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
  </tr>

  <% @garage.each do |garage| %>
  <tr>
    <td><%= garage.make %></td>
    <td><%= garage.model %></td>
    <td><%= garage.year %></td>
    <td><%= link_to 'View', garage_path(garage) %></td>
    <td><%= link_to 'Edit', edit_garage_path(garage) %></td>
    <td><%= link_to 'Sell Vehicle', garage_path(garage),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/garage/new.html.erb
<h1>My Garage </h1>
<h3>Add your vehicle<h3>

  <%= render 'form' %>

  <%= link_to 'Back to Garage', garage_index_path %>

app/views/garage/show.html.erb
<p>
  <strong>Make:</strong>
  <%= @garage.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @garage.model %>
</p>
<p>
  <strong>Year:</strong>
  <%= @garage.year %>
</p>
<%= link_to 'Edit', edit_garage_path(@garage) %> 
<%= link_to 'Back to Garage', garage_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGarage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>


  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this User from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<%= link_to 'New User', new_user_path %>
<table>
  <tr>
    <th>Name </th>

  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.user %></td>
      <td><%= link_to 'View', user_path(user) %></td>
      <td><%= link_to 'Edit User', edit_user_path(user) %></td>
      <td><%= link_to 'Delete User', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for :user, url: users_path do |f| %>
<% if @user.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@user.errors.count, "error") %> prohibited
       this User from being saved:
     </h2>
     <ul>
       <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
  <p>
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

  <%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>User:</strong>
  <%= @user.user %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1> Welcome to My Garage!<h1>
<h3>Please sign up below</h3>

<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>